version: '3.8'

services:
  aws-agent:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - AWS_REGION=us-east-1
